# https://taskfile.dev

version: "3"

tasks:
  mock:
    desc: Generate mocks
    cmds:
      - mockgen -destination storage/mock/storage.go -package mock github.com/dcbltech/go-kit/storage Storage
      - mockgen -destination tts/mock/tts.go -package mock github.com/dcbltech/go-kit/tts TextToSpeech
      - mockgen -destination email/mock/email.go -package mock github.com/dcbltech/go-kit/email Emailer
